version: "3.5"

services:
  shorty:
    domainname: shorty.local
    container_name: shorty_app
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    networks:
      - shortynet

  mysql:
    domainname: mysql.local.shorty
    container_name: shorty_mysql
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: shorty
    networks:
      shortynet:
        aliases:
          - mysql.local.shorty

networks:
  shortynet:
