version: "3.5"

services:
  shorty:
    domainname: shorty.local
    container_name: shorty_app
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    networks:
      - shortynet

  postgres:
    domainname: postgres.local.shorty
    container_name: shorty_postgres
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin
    networks:
      shortynet:
        aliases:
          - postgres.local.shorty

networks:
  shortynet:
